language: php
php:
  - 7.1
before_script:
  - phpenv config-rm xdebug.ini
  - pecl install dio-beta
  - composer global require hirak/prestissimo
  - composer install --no-scripts --no-suggest
script:
  - vendor/bin/phpcs --standard=vendor/nocworx/phpcs/ruleset.xml src web
